/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelDominio.Usuario;
import view.util.ComboBox;

/**
 *
 * @author Kauany
 */
public class FormUsuarios extends javax.swing.JDialog {

    private int codigo;
    private int tipo;


    ArrayList<Usuario> listaUsuarios;

    private void carregaCombo() {
        // preenchendo o comboBox das marcas
        listaUsuarios = new ArrayList<Usuario>();
        listaUsuarios = BottonsCliente.ccont.listaUsuarios("");
        ComboBox.preencheComboBox(-1, cmbUsuario, listaUsuarios, false);
    }

    public FormUsuarios() {
        initComponents();
        carregaCombo();
        carregaDadosUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLnome = new javax.swing.JLabel();
        jLcpf = new javax.swing.JLabel();
        jTFCPF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jRBSim = new javax.swing.JRadioButton();
        JRBNao = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jBSalvar = new javax.swing.JButton();
        cmbUsuario = new javax.swing.JComboBox<>();
        jRBAtivo = new javax.swing.JRadioButton();
        JRBDesativo = new javax.swing.JRadioButton();
        jBNovo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTFEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jBVoltar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTFLogin = new javax.swing.JTextField();
        JPFsenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuários");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLnome.setText("Usuário:");

        jLcpf.setText("CPF:");

        jTFCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCPFActionPerformed(evt);
            }
        });

        jLabel1.setText("Administrador:");

        buttonGroup1.add(jRBSim);
        jRBSim.setText("Sim");

        buttonGroup1.add(JRBNao);
        JRBNao.setText("Não");

        jLabel2.setText("Excluir:");

        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        cmbUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbUsuario.setToolTipText("");
        cmbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUsuarioActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRBAtivo);
        jRBAtivo.setText("Não");
        jRBAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBAtivoActionPerformed(evt);
            }
        });

        buttonGroup3.add(JRBDesativo);
        JRBDesativo.setText("Excluir");

        jBNovo.setText("Novo");
        jBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNovoActionPerformed(evt);
            }
        });

        jLabel4.setText("Email:");

        jLabel3.setText("Nome:");

        jTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomeActionPerformed(evt);
            }
        });

        jBVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/icons8-back-arrow-30.png"))); // NOI18N
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jLabel6.setText("Senha:");

        jLabel5.setText("Login:");

        jTFLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFLoginActionPerformed(evt);
            }
        });

        JPFsenha.setText("jPasswordField1");
        JPFsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPFsenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBNovo)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLcpf)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLnome)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JPFsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBSalvar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRBSim)
                                    .addComponent(JRBDesativo))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(JRBNao))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jRBAtivo)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBNovo)
                    .addComponent(jBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLnome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JPFsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLcpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRBSim)
                    .addComponent(JRBNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JRBDesativo)
                    .addComponent(jRBAtivo))
                .addGap(29, 29, 29)
                .addComponent(jBSalvar)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUsuarioActionPerformed
        carregaDadosUsuario();

    }//GEN-LAST:event_cmbUsuarioActionPerformed

    public void carregaDadosUsuario() {
        int posicao = cmbUsuario.getSelectedIndex();
        Usuario usr = listaUsuarios.get(posicao);

        this.codigo = usr.getCodUsuario();
        jTFNome.setText(usr.getNomeusuario());
        jTFCPF.setText(usr.getCpf());
        jTFEmail.setText(usr.getEmail());
        jTFLogin.setText(usr.getLogin());
        JPFsenha.setText("");
        int tipo = usr.getTipo();
        jRBAtivo.setSelected(true);

        if (tipo == 1) {
            jRBSim.setSelected(true);
        } else {
            JRBNao.setSelected(true);
        }
    }

    private void jBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoActionPerformed
        FormCadastroUsuario frcd = new FormCadastroUsuario();
        frcd.setModal(true);
        frcd.setVisible(true);
        carregaDadosUsuario();

    }//GEN-LAST:event_jBNovoActionPerformed

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        if (!jTFNome.equals("")) {
            if (!jTFLogin.equals("")) {
//                if (!JPFsenha.equals("")) {
                if (!jTFEmail.equals("")) {
                    if (!jTFCPF.equals("")) {
                        if (jRBSim.isSelected() || JRBNao.isSelected()) {
                            if (jRBAtivo.isSelected() || JRBDesativo.isSelected()) {

                                String nome = jTFNome.getText();
                                String login = jTFLogin.getText();
                                String email = jTFEmail.getText();
                                String cpf = jTFCPF.getText();
                                String senha = JPFsenha.getText();

                                // metodo para desativar/excluir
                                if (JRBDesativo.isSelected()) {
                                    if (JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir?",
                                            this.getTitle(), JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                                        int posicao = cmbUsuario.getSelectedIndex();
                                        Usuario usr = listaUsuarios.get(posicao);
                                        if (usr != null) {
                                            BottonsCliente.ccont.excluirUsuario(usr);
                                            JOptionPane.showMessageDialog(this, "Usuário excluído com sucesso!", this.getTitle(),
                                                    JOptionPane.INFORMATION_MESSAGE);
                                            carregaCombo();

                                        } else {
                                            JOptionPane.showMessageDialog(this, "Erro ao excluir usuário!", this.getTitle(),
                                                    JOptionPane.ERROR_MESSAGE);
                                        }
                                    }

                                    //alterar usuario
                                } else if (JOptionPane.showConfirmDialog(this, "Tem certeza que deseja alterar?",
                                        this.getTitle(), JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                                    if (jRBSim.isSelected()) {
                                        tipo = 1;
                                    } else if (JRBNao.isSelected()) {
                                        tipo = 2;
                                    }

                                    int posicao = cmbUsuario.getSelectedIndex();
                                    Usuario usr = listaUsuarios.get(posicao);
                                    // ???????????????????????
                                    usr = new Usuario(codigo, nome, login, senha, email, cpf, tipo);
                                    boolean ok = BottonsCliente.ccont.alterarUsuario(usr);
                                    System.out.println(usr);

                                    if (ok) {
                                        JOptionPane.showMessageDialog(this, "Usuário alterado com sucesso", this.getTitle(),
                                                JOptionPane.INFORMATION_MESSAGE);
                                        carregaDadosUsuario();

                                    } else {
                                        JOptionPane.showMessageDialog(this, "Erro ao alterar usuário", this.getTitle(),
                                                JOptionPane.ERROR_MESSAGE);

                                    }

                                }

                            } else {
                                JOptionPane.showMessageDialog(this, "Selecione um estado!", this.getTitle(), JOptionPane.ERROR_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Selecione um tipo!", this.getTitle(), JOptionPane.ERROR_MESSAGE);
                        }

                    } else {
                        JOptionPane.showMessageDialog(this, "Prencha o campo: CPF!", this.getTitle(), JOptionPane.ERROR_MESSAGE);
                        jTFCPF.requestFocus();
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Prencha o campo: Email!", this.getTitle(), JOptionPane.ERROR_MESSAGE);
                    jTFEmail.requestFocus();
                }
//
//                } else {
//                    JOptionPane.showMessageDialog(this, "Prencha o campo: Senha!", this.getTitle(), JOptionPane.ERROR_MESSAGE);
//                    JPFsenha.requestFocus();
//                }
            } else {
                JOptionPane.showMessageDialog(this, "Prencha o campo: Login!", this.getTitle(), JOptionPane.ERROR_MESSAGE);
                jTFLogin.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Prencha o campo: Nome!", this.getTitle(), JOptionPane.ERROR_MESSAGE);
            jTFNome.requestFocus();
        }

    }//GEN-LAST:event_jBSalvarActionPerformed
    public void limpaCampos() {
        jTFNome.setText("");
        jTFLogin.setText("");
        JPFsenha.setText("");
        jTFEmail.setText("");
        jTFCPF.setText("");
    }
    private void jRBAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBAtivoActionPerformed

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jTFCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCPFActionPerformed

    private void jTFLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFLoginActionPerformed

    private void JPFsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPFsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPFsenhaActionPerformed

    private void jTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JPFsenha;
    private javax.swing.JRadioButton JRBDesativo;
    private javax.swing.JRadioButton JRBNao;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cmbUsuario;
    private javax.swing.JButton jBNovo;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLcpf;
    private javax.swing.JLabel jLnome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBAtivo;
    private javax.swing.JRadioButton jRBSim;
    private javax.swing.JTextField jTFCPF;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFLogin;
    private javax.swing.JTextField jTFNome;
    // End of variables declaration//GEN-END:variables
}
